图层:
    L0-白天:
        特殊标记: "基底"
    L1-傍晚:
        特殊标记: "基底"
    L2-夜晚关灯:
        特殊标记: "基底"
    L3-夜晚开灯:
        特殊标记: "基底"
元数据:
    author: "考拉Koala"
    license: "cc0"
    overview_scale: 0.125
