include: "../T_config_common.yml"
选区:
    M0-屏幕:
        基础颜色: "#9dbfe6"
        图像坐标:
            左上: [1480, 759]
            右上: [3519, 759]
            左下: [1471,1891]
            右下: [3528,1891]
    M1-底座:
        基础颜色: "#9396a4"
