图层:
    L0-白天:
        特殊标记: "基底"
    L1-傍晚:
        特殊标记: "基底"
    L2-夜晚_关灯:
        特殊标记: "基底"
    L3-夜晚_开灯:
        特殊标记: "基底"
选区:
    M0-屏幕:
        基础颜色: "#9dbfe6"
        图像坐标:
            左上: [1480, 759]
            右上: [3519, 759]
            左下: [1471,1891]
            右下: [3528,1891]
    M1-底座:
        基础颜色: "#9396a4"
元数据:
    author: "考拉Koala"
    license: "cc0"
    overview_scale: 0.125
