选区:
  M1-头发:
    基础颜色: "#c3c3cd"
    适用于: ["L1-后发", "L15-垂发", "L17-前发"]
  M2-衣服:
    基础颜色: "#4e5357"
    适用于:
      - LC801-普通姿势衣后-左侧上臂衣袖
      - LC803-普通姿势衣后-左侧袖口
      - LC805-普通姿势衣后-左侧前臂衣袖
      - LC807-普通姿势衣后-右侧袖口
      - LC809-普通姿势衣后-右侧衣袖
      - LC901-抬手姿势衣后-左侧上臂衣袖
      - LC903-抬手姿势衣后-右侧衣袖
      - L10-抱胸姿势衣后
      - LC1101-黑衣服松-底
      - LC1201-黑衣服紧-底
      - LC1301-抬手姿势衣前-袖口
      - LC1303-抬手姿势衣前-左侧衣袖
      - LC1401-抱胸姿势衣前-左侧前臂衣袖
      - LC1403-抱胸姿势衣前-右侧前臂袖口
      - LC1405-抱胸姿势衣前-右侧衣袖
  M3-衣服装饰:
    基础颜色: "#93a0eb"
    适用于:
      - LC806-普通姿势衣后-左侧前臂衣袖条纹
      - LC810-普通姿势衣后-右侧衣袖条纹
      - LC904-抬手姿势衣后-右侧衣袖条纹
      - LC1102-黑衣服松-左扣2
      - LC1103-黑衣服松-左扣1
      - LC1104-黑衣服松-左口袋
      - LC1105-黑衣服松-右扣2
      - LC1106-黑衣服松-右扣1
      - LC1107-黑衣服松-右口袋
      - LC1108-黑衣服松-右上装饰
      - LC1202-黑衣服紧-左扣2
      - LC1203-黑衣服紧-左扣1
      - LC1204-黑衣服紧-左口袋
      - LC1205-黑衣服紧-右扣2
      - LC1206-黑衣服紧-右扣1
      - LC1207-黑衣服紧-右口袋
      - LC1208-黑衣服紧-右上装饰
      - LC1304-抬手姿势衣前-左侧衣袖条纹
      - LC1402-抱胸姿势衣前-左侧前臂衣袖条纹
      - LC1406-抱胸姿势衣前-右侧衣袖条纹
  M4-裙子:
    基础颜色: "#eaebed"
    适用于: ["L4-白衣底", "L6-白衣底2"]
  M5-裙子图案:
    基础颜色: "#426e9e"
    适用于: ["L5-白衣图案", "L7-白衣图案2"]
生成:
  charactersprite_parts_based:
    部件类型:
      B1: preset_kind_base
      B2: preset_kind_base
      M: preset_kind_eyebrow
      Y: preset_kind_eye
      K: preset_kind_mouth
      #Q: preset_kind_fullface
      DK1: preset_kind_decoration
      DK2: preset_kind_decoration
    标签:
      通用: preset_tag_general
      笑容: preset_tag_smile
      愤怒: preset_tag_angry
      悲伤: preset_tag_sad
      惊讶: preset_tag_surprised
      困惑: preset_tag_confused
      害怕: preset_tag_scared
      基底-普通: preset_tag_base
      基底-抬手: preset_tag_base
      基底-抱胸: preset_tag_base
    部件: # 按图层顺序，从下到上
      B1:
        L1-后发: ["基底-普通", "基底-抬手", "基底-抱胸"]
        L2-腿: ["基底-普通", "基底-抬手", "基底-抱胸"]
        L3-脖子: ["基底-普通", "基底-抬手", "基底-抱胸"]
        L4-白衣底: ["基底-普通"]
        L5-白衣图案: ["基底-普通"]
        L6-白衣底2: ["基底-抬手", "基底-抱胸"]
        L7-白衣图案2: ["基底-抬手", "基底-抱胸"]
        # L8-普通姿势衣后: 基底-普通
        LC801-普通姿势衣后-左侧上臂衣袖: 基底-普通
        LC802-普通姿势衣后-本子: 基底-普通
        LC803-普通姿势衣后-左侧袖口: 基底-普通
        LC804-普通姿势衣后-左侧手: 基底-普通
        LC805-普通姿势衣后-左侧前臂衣袖: 基底-普通
        LC806-普通姿势衣后-左侧前臂衣袖条纹: 基底-普通
        LC807-普通姿势衣后-右侧袖口: 基底-普通
        LC808-普通姿势衣后-右侧手: 基底-普通
        LC809-普通姿势衣后-右侧衣袖: 基底-普通
        LC810-普通姿势衣后-右侧衣袖条纹: 基底-普通
        # L9-抬手姿势衣后: 基底-抬手
        LC901-抬手姿势衣后-左侧上臂衣袖: 基底-抬手
        LC902-抬手姿势衣后-右侧手: 基底-抬手
        LC903-抬手姿势衣后-右侧衣袖: 基底-抬手
        LC904-抬手姿势衣后-右侧衣袖条纹: 基底-抬手
        L10-抱胸姿势衣后: 基底-抱胸
        # L11-黑衣服松: ["基底-普通"]
        LC1101-黑衣服松-底: ["基底-普通"]
        LC1102-黑衣服松-左扣2: ["基底-普通"]
        LC1103-黑衣服松-左扣1: ["基底-普通"]
        LC1104-黑衣服松-左口袋: ["基底-普通"]
        LC1105-黑衣服松-右扣2: ["基底-普通"]
        LC1106-黑衣服松-右扣1: ["基底-普通"]
        LC1107-黑衣服松-右口袋: ["基底-普通"]
        LC1108-黑衣服松-右上装饰: ["基底-普通"]
        # L12-黑衣服紧: ["基底-抬手", "基底-抱胸"]
        LC1201-黑衣服紧-底: ["基底-抬手", "基底-抱胸"]
        LC1202-黑衣服紧-左扣2: ["基底-抬手", "基底-抱胸"]
        LC1203-黑衣服紧-左扣1: ["基底-抬手", "基底-抱胸"]
        LC1204-黑衣服紧-左口袋: ["基底-抬手", "基底-抱胸"]
        LC1205-黑衣服紧-右扣2: ["基底-抬手", "基底-抱胸"]
        LC1206-黑衣服紧-右扣1: ["基底-抬手", "基底-抱胸"]
        LC1207-黑衣服紧-右口袋: ["基底-抬手", "基底-抱胸"]
        LC1208-黑衣服紧-右上装饰: ["基底-抬手", "基底-抱胸"]
        # L13-抬手姿势衣前: 基底-抬手
        LC1301-抬手姿势衣前-袖口: 基底-抬手
        LC1302-抬手姿势衣前-左侧手: 基底-抬手
        LC1303-抬手姿势衣前-左侧衣袖: 基底-抬手
        LC1304-抬手姿势衣前-左侧衣袖条纹: 基底-抬手
        # L14-抱胸姿势衣前: 基底-抱胸
        LC1401-抱胸姿势衣前-左侧前臂衣袖: 基底-抱胸
        LC1402-抱胸姿势衣前-左侧前臂衣袖条纹: 基底-抱胸
        LC1403-抱胸姿势衣前-右侧前臂袖口: 基底-抱胸
        LC1404-抱胸姿势衣前-右侧手: 基底-抱胸
        LC1405-抱胸姿势衣前-右侧衣袖: 基底-抱胸
        LC1406-抱胸姿势衣前-右侧衣袖条纹: 基底-抱胸
        LC1407-抱胸姿势衣前-左侧手: 基底-抱胸
        L15-垂发: ["基底-普通", "基底-抬手", "基底-抱胸"]
        L16-脸底: ["基底-普通", "基底-抬手", "基底-抱胸"]
        L17-前发: ["基底-普通", "基底-抬手", "基底-抱胸"]
      K:
        K2-正常-闭嘴: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        K3-正常-微张: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        K4-正常-张嘴: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        K5-微笑-闭嘴: ["笑容"]
        K6-微笑-张嘴: ["笑容"]
        K7-欢呼: ["笑容"]
        K8-夸张笑: ["笑容"]
        K9-坏笑-闭嘴: ["笑容"]
        K10-生气-闭嘴: ["愤怒"]
        K11-生气-呵斥: ["愤怒"]
        K12-生气-嘟嘴: ["愤怒"]
        K13-生气-咬牙: ["愤怒"]
        K14-吐槽张嘴: ["愤怒", "惊讶"]
        K15-悲伤失望-叹气: ["悲伤"]
        K16-悲伤失望-微张嘴: ["悲伤"]
        K17-惊讶-张大嘴巴: ["惊讶"]
        K18-悲伤害怕-张嘴: ["悲伤", "害怕"]
        K19-悲伤害怕-微张嘴: ["悲伤", "害怕"]
        K20-悲伤害怕-闭嘴: ["悲伤", "害怕"]
        K21-吐舌头: ["笑容"]
        K22-吐槽噘嘴: ["通用", "愤怒"]
        TK1-正常说话啊: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        TK2-正常说话哦: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        TK3-悲伤害怕扭曲B: ["悲伤", "害怕"]
        TK6-吃惊进阶: ["惊讶"]
        TK7-生气咬牙2: ["愤怒"]
        TK8-微笑-嘴角微翘: ["笑容"]
        TK9-自然笑: ["笑容"]
        QK1-状态不佳嘴巴: ["悲伤"]
        QK2-哭泣嘴巴: ["悲伤", "害怕"]
        QK3-怒笑嘴巴: ["笑容", "愤怒"]
        QK4-疼痛嘴巴: ["悲伤"]
        QK5-怒斥嘴巴: ["愤怒"]
        QK6-狂笑嘴巴: ["笑容"]
        QK7-苦笑嘴巴: ["笑容", "悲伤"]
        QK8-狂笑咧嘴嘴巴: ["笑容"]
      B2:
        L18-鼻子: ["基底-普通", "基底-抬手", "基底-抱胸"]
        L19-腮红底: ["基底-普通", "基底-抬手", "基底-抱胸"]
      DK1:
        D5-脸红: ["通用"]
      Y:
        Y2-正常-睁眼: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        Y3-正常-闭眼: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        Y4-正常-瞥向下方: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        Y5-正常-瞥向左侧: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        Y6-失神: ["通用"]
        Y7-微笑-睁眼: ["笑容"]
        Y8-微笑-瞥向左侧: ["笑容"]
        Y9-微笑-闭眼: ["笑容"]
        Y10-严肃-睁眼: ["愤怒"]
        Y11-严肃-瞥向左侧: ["愤怒"]
        Y12-生气-凶狠: ["愤怒"]
        Y13-悲伤担忧害怕-睁眼: ["悲伤", "害怕"]
        Y14-悲伤担忧害怕-瞥向右侧: ["悲伤", "害怕"]
        Y15-悲伤担忧害怕-闭眼: ["悲伤", "害怕"]
        Y16-惊讶-睁大眼睛: ["惊讶"]
        Y17-惊讶-睁眼: ["惊讶"]
        Y18-紧张-睁眼: ["惊讶", "害怕"]
        Y19-大小眼: ["困惑"]
        Y20-疲劳: ["通用", "悲伤"]
        Y22-颜艺-眼睛放光: ["笑容"]
        Y23-颜艺-闭眼: ["笑容", "悲伤", "害怕"]
        Y24-颜艺-神游: ["笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        Y25-颜艺-泪眼婆娑: ["笑容", "悲伤", "害怕"]
        Y26-颜艺-泪流满面: ["笑容", "悲伤", "害怕"]
        Y27-颜艺-迷糊眼: ["通用"]
        Y28-颜艺-无语: ["通用", "愤怒"]
        Y29-颜艺-吐槽: ["通用", "愤怒"]
        Y30-颜艺-陶醉: ["通用", "笑容"]
        TY1-严肃瞥向下方: ["愤怒"]
        TY2-向上看: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        TY3-大笑-睁眼: ["笑容"]
        TY4-认真: ["通用", "愤怒"]
        TY5-颜艺-无语2: ["通用", "愤怒"]
        TY6-调皮眼: ["笑容"]
        QY1-状态不佳眼睛: ["悲伤"]
        QY2-哭泣眼睛: ["悲伤", "害怕"]
        QY3-怒笑眼睛: ["笑容", "愤怒"]
        QY4-疼痛眼睛: ["悲伤"]
        QY5-怒斥眼睛: ["愤怒"]
        QY6-狂笑眼睛: ["笑容"]
        QY7-苦笑眼睛: ["笑容", "悲伤"]
        QY8-狂笑咧嘴眼睛: ["笑容"]
      M:
        M2-正常: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        M3-大笑-得意: ["笑容"]
        M4-严肃生气: ["愤怒"]
        M5-愤怒: ["愤怒"]
        M6-悲伤无奈: ["悲伤"]
        M7-惊讶: ["惊讶"]
        M8-困惑: ["困惑"]
        M9-害怕: ["害怕"]
        M10-正常-低位: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        M11-害羞: ["笑容", "害怕"]
        M12-坏笑: ["笑容"]
        TM1-忧伤困惑: ["悲伤", "困惑"]
        TM2-严肃生气2: ["愤怒"]
        TM3-严肃生气3: ["愤怒"]
        TM5-正常高位: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        TM6-平眉: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        TM7-忧伤: ["悲伤"]
        TM8-害怕2: ["害怕"]
        TM9-平眉高位: ["通用", "笑容", "愤怒", "悲伤", "惊讶", "困惑", "害怕"]
        TM10-高低眉毛2: ["笑容"]
        QM1-状态不佳眉毛: ["悲伤"]
        QM2-哭泣眉毛: ["悲伤", "害怕"]
        QM3-怒笑眉毛: ["笑容", "愤怒"]
        QM4-疼痛眉毛: ["悲伤"]
        QM5-怒斥眉毛: ["愤怒"]
        QM6-狂笑眉毛: ["笑容"]
        QM7-苦笑眉毛: ["笑容", "悲伤"]
      DK2:
        D2-汗颜: ["通用", "笑容"]
        D3-愤怒-青筋暴出: ["通用", "笑容", "愤怒"]
        D4-炸毛: ["惊讶", "害怕"]
        # D5-脸红 在DK1中
        D6-叹气: ["通用"]
        D7-阴沉阴影: ["通用", "愤怒", "悲伤", "害怕"]
        TD1-问号: ["通用", "困惑"]
        TD2-状态不佳阴影: ["害怕"]
        TD3-鼻上阴影: ["害怕"]
    基底简写:
      # L8: LC801LC802LC803LC804LC805LC806LC807LC808LC809LC810
      # L9: LC901LC902LC903LC904
      # L11: LC1101LC1102LC1103LC1104LC1105LC1106LC1107LC1108
      # L12: LC1201LC1202LC1203LC1204LC1205LC1206LC1207LC1208
      # L13: LC1301LC1302LC1303LC1304
      # L14: LC1401LC1402LC1403LC1404LC1405LC1406LC1407
      B0: L1L2L3L4L5LC801LC802LC803LC804LC805LC806LC807LC808LC809LC810LC1101LC1102LC1103LC1104LC1105LC1106LC1107LC1108L15L16L17L18L19
      B1: L1L2L3L6L7LC901LC902LC903LC904LC1201LC1202LC1203LC1204LC1205LC1206LC1207LC1208LC1301LC1302LC1303LC1304L15L16L17L18L19
      B2: L1L2L3L6L7L10LC1201LC1202LC1203LC1204LC1205LC1206LC1207LC1208LC1401LC1402LC1403LC1404LC1405LC1406LC1407L15L16L17L18L19
元数据:
    author: "Aixuanx"
    license: "cc0"
    overview_scale: 0.1
    diff_croprect: [3740, 2327, 4710, 3297]

