图层:
    L0-白天:
        特殊标记: "基底"
    L1-傍晚:
        特殊标记: "基底"
    L2-夜晚_关灯:
        特殊标记: "基底"
    L3-夜晚_开灯:
        特殊标记: "基底"
选区:
    M0-屏幕:
        基础颜色: "#fff0db"
        图像坐标:
            左上: [1413, 804]
            右上: [3586, 804]
            左下: [1409,2028]
            右下: [3590,2028]
    M1-背景:
        基础颜色: "#edc7ac"
元数据:
    author: "考拉Koala"
    license: "cc0"
    overview_scale: 0.125
