include: "../T_config_common.yml"
选区:
    M0-屏幕:
        基础颜色: "#fff0db"
        图像坐标:
            左上: [1413, 804]
            右上: [3586, 804]
            左下: [1409,2028]
            右下: [3590,2028]
    M1-背景:
        基础颜色: "#edc7ac"
