图层:
    L0-白天:
        特殊标记: "基底"
    L1-傍晚:
        特殊标记: "基底"
    L2-夜晚_关灯:
        特殊标记: "基底"
    L3-夜晚_开灯:
        特殊标记: "基底"
选区:
    M0-屏幕:
        基础颜色: "#ffeddf"
        图像坐标:
            左上: [1662, 651]
            右上: [3495, 651]
            左下: [1667,1680]
            右下: [3489,1680]
    M1-地毯:
        基础颜色: "#fff2d2"
元数据:
    author: "考拉Koala"
    license: "cc0"
    overview_scale: 0.125
