include: "../T_config_common.yml"
选区:
    M0-屏幕:
        基础颜色: "#ffeddf"
        图像坐标:
            左上: [1662, 651]
            右上: [3495, 651]
            左下: [1667,1680]
            右下: [3489,1680]
    M1-地毯:
        基础颜色: "#fff2d2"
